<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ExtensionsEntry\readme.txt" />
    <None Remove="ImageCache\readme.txt" />
    <None Remove="Publics\defalut.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ExtensionsEntry\readme.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageCache\readme.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Publics\defalut.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Extensions\Extensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- MediatR -->
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.5.2" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
    <!-- Microsoft.Extensions 核心包 -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.AutoActivation" Version="9.9.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    
    <!-- System.Reactive (简化，只保留主包) -->
    <PackageReference Include="System.Reactive" Version="6.0.2" />
  </ItemGroup>
</Project>